name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: What would you like to see?
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Why?
      description: How would this improve Golazo?
      placeholder: "This would help because..."
    validations:
      required: true
