Output golazo-demo.gif
Set FontSize 10
Set Width 1000
Set Height 700
Set Theme "3024 Night"

Type "./golazo-demo"
Enter
Sleep 500ms

# Navigation
Down
Sleep 300ms
Down
Sleep 300ms
Up
Sleep 300ms


# Main view, select live
Enter
Down
Up
Sleep 300ms


# Navigate live list
Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 2s
Down
Sleep 2s

# Back to main view
Escape

# Select Finished Matches
Enter
Sleep 1.5s

# Navigate list (5 matches)
Down
Sleep 1.5s
Down
Sleep 1.5s
Down
Sleep 1.5s